/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AthkarRouteImport } from './routes/athkar'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as ContestRouteImport } from './routes/contest'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as HadithRouteImport } from './routes/hadith'
import { Route as MemorizeRouteImport } from './routes/memorize'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PageRouteImport } from './routes/page'
import { Route as PrayerRouteImport } from './routes/prayer'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as ReadRouteImport } from './routes/read'
import { Route as ReciteRouteImport } from './routes/recite'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SiraRouteImport } from './routes/sira'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TafsirRouteImport } from './routes/tafsir'
import { Route as TasbihRouteImport } from './routes/tasbih'
import { Route as ToolsRouteImport } from './routes/tools'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AthkarRoute = AthkarRouteImport.update({
  id: '/athkar',
  path: '/athkar',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestRoute = ContestRouteImport.update({
  id: '/contest',
  path: '/contest',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithRoute = HadithRouteImport.update({
  id: '/hadith',
  path: '/hadith',
  getParentRoute: () => rootRouteImport,
} as any)
const MemorizeRoute = MemorizeRouteImport.update({
  id: '/memorize',
  path: '/memorize',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/page',
  path: '/page',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerRoute = PrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadRoute = ReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ReciteRoute = ReciteRouteImport.update({
  id: '/recite',
  path: '/recite',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SiraRoute = SiraRouteImport.update({
  id: '/sira',
  path: '/sira',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TafsirRoute = TafsirRouteImport.update({
  id: '/tafsir',
  path: '/tafsir',
  getParentRoute: () => rootRouteImport,
} as any)
const TasbihRoute = TasbihRouteImport.update({
  id: '/tasbih',
  path: '/tasbih',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/athkar': typeof AthkarRoute
  '/bookmarks': typeof BookmarksRoute
  '/contest': typeof ContestRoute
  '/dashboard': typeof DashboardRoute
  '/downloads': typeof DownloadsRoute
  '/feedback': typeof FeedbackRoute
  '/hadith': typeof HadithRoute
  '/memorize': typeof MemorizeRoute
  '/onboarding': typeof OnboardingRoute
  '/page': typeof PageRoute
  '/prayer': typeof PrayerRoute
  '/radio': typeof RadioRoute
  '/read': typeof ReadRoute
  '/recite': typeof ReciteRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sira': typeof SiraRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tafsir': typeof TafsirRoute
  '/tasbih': typeof TasbihRoute
  '/tools': typeof ToolsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/athkar': typeof AthkarRoute
  '/bookmarks': typeof BookmarksRoute
  '/contest': typeof ContestRoute
  '/dashboard': typeof DashboardRoute
  '/downloads': typeof DownloadsRoute
  '/feedback': typeof FeedbackRoute
  '/hadith': typeof HadithRoute
  '/memorize': typeof MemorizeRoute
  '/onboarding': typeof OnboardingRoute
  '/page': typeof PageRoute
  '/prayer': typeof PrayerRoute
  '/radio': typeof RadioRoute
  '/read': typeof ReadRoute
  '/recite': typeof ReciteRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sira': typeof SiraRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tafsir': typeof TafsirRoute
  '/tasbih': typeof TasbihRoute
  '/tools': typeof ToolsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/athkar': typeof AthkarRoute
  '/bookmarks': typeof BookmarksRoute
  '/contest': typeof ContestRoute
  '/dashboard': typeof DashboardRoute
  '/downloads': typeof DownloadsRoute
  '/feedback': typeof FeedbackRoute
  '/hadith': typeof HadithRoute
  '/memorize': typeof MemorizeRoute
  '/onboarding': typeof OnboardingRoute
  '/page': typeof PageRoute
  '/prayer': typeof PrayerRoute
  '/radio': typeof RadioRoute
  '/read': typeof ReadRoute
  '/recite': typeof ReciteRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sira': typeof SiraRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tafsir': typeof TafsirRoute
  '/tasbih': typeof TasbihRoute
  '/tools': typeof ToolsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/athkar'
    | '/bookmarks'
    | '/contest'
    | '/dashboard'
    | '/downloads'
    | '/feedback'
    | '/hadith'
    | '/memorize'
    | '/onboarding'
    | '/page'
    | '/prayer'
    | '/radio'
    | '/read'
    | '/recite'
    | '/search'
    | '/settings'
    | '/sira'
    | '/sitemap.xml'
    | '/tafsir'
    | '/tasbih'
    | '/tools'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/athkar'
    | '/bookmarks'
    | '/contest'
    | '/dashboard'
    | '/downloads'
    | '/feedback'
    | '/hadith'
    | '/memorize'
    | '/onboarding'
    | '/page'
    | '/prayer'
    | '/radio'
    | '/read'
    | '/recite'
    | '/search'
    | '/settings'
    | '/sira'
    | '/sitemap.xml'
    | '/tafsir'
    | '/tasbih'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/athkar'
    | '/bookmarks'
    | '/contest'
    | '/dashboard'
    | '/downloads'
    | '/feedback'
    | '/hadith'
    | '/memorize'
    | '/onboarding'
    | '/page'
    | '/prayer'
    | '/radio'
    | '/read'
    | '/recite'
    | '/search'
    | '/settings'
    | '/sira'
    | '/sitemap.xml'
    | '/tafsir'
    | '/tasbih'
    | '/tools'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  AthkarRoute: typeof AthkarRoute
  BookmarksRoute: typeof BookmarksRoute
  ContestRoute: typeof ContestRoute
  DashboardRoute: typeof DashboardRoute
  DownloadsRoute: typeof DownloadsRoute
  FeedbackRoute: typeof FeedbackRoute
  HadithRoute: typeof HadithRoute
  MemorizeRoute: typeof MemorizeRoute
  OnboardingRoute: typeof OnboardingRoute
  PageRoute: typeof PageRoute
  PrayerRoute: typeof PrayerRoute
  RadioRoute: typeof RadioRoute
  ReadRoute: typeof ReadRoute
  ReciteRoute: typeof ReciteRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SiraRoute: typeof SiraRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TafsirRoute: typeof TafsirRoute
  TasbihRoute: typeof TasbihRoute
  ToolsRoute: typeof ToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athkar': {
      id: '/athkar'
      path: '/athkar'
      fullPath: '/athkar'
      preLoaderRoute: typeof AthkarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contest': {
      id: '/contest'
      path: '/contest'
      fullPath: '/contest'
      preLoaderRoute: typeof ContestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith': {
      id: '/hadith'
      path: '/hadith'
      fullPath: '/hadith'
      preLoaderRoute: typeof HadithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memorize': {
      id: '/memorize'
      path: '/memorize'
      fullPath: '/memorize'
      preLoaderRoute: typeof MemorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page': {
      id: '/page'
      path: '/page'
      fullPath: '/page'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer': {
      id: '/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof PrayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read': {
      id: '/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof ReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recite': {
      id: '/recite'
      path: '/recite'
      fullPath: '/recite'
      preLoaderRoute: typeof ReciteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sira': {
      id: '/sira'
      path: '/sira'
      fullPath: '/sira'
      preLoaderRoute: typeof SiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tafsir': {
      id: '/tafsir'
      path: '/tafsir'
      fullPath: '/tafsir'
      preLoaderRoute: typeof TafsirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasbih': {
      id: '/tasbih'
      path: '/tasbih'
      fullPath: '/tasbih'
      preLoaderRoute: typeof TasbihRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  AthkarRoute: AthkarRoute,
  BookmarksRoute: BookmarksRoute,
  ContestRoute: ContestRoute,
  DashboardRoute: DashboardRoute,
  DownloadsRoute: DownloadsRoute,
  FeedbackRoute: FeedbackRoute,
  HadithRoute: HadithRoute,
  MemorizeRoute: MemorizeRoute,
  OnboardingRoute: OnboardingRoute,
  PageRoute: PageRoute,
  PrayerRoute: PrayerRoute,
  RadioRoute: RadioRoute,
  ReadRoute: ReadRoute,
  ReciteRoute: ReciteRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SiraRoute: SiraRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TafsirRoute: TafsirRoute,
  TasbihRoute: TasbihRoute,
  ToolsRoute: ToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
